spring:
  application:
    name: NBE_5_7_2_02TEAM

  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create


  security:
    oauth2:
      client:
        registration:
          github:
            client-name: GitHub
            client-id: Ov23li06as0VfMDE0kwl
            client-secret: 9055bc9dc2f567678376f8f3e11e4c7b2c3d3695
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - read:user
              - user:email
              - read:org

file:
  upload-dir: uploads/

custom:
  jwt:
    validation:
      access: ${JWT_ACCESS_EXP}
      refresh: ${JWT_REFRESH_EXP}
    redirection:
      base: http://localhost:5173/callback
    secrets:
      origin-key: ${JWT_ORIGIN_KEY}
      app-key: ${JWT_APP_KEY}